language: python
python:
  - 2.7

sudo: required

os:
  - linux

services:
  - docker

install:
  - docker build -t mit6881 -f ubuntu16_04_mit6881.dockerfile .

script:
  - python ./docker_run.py --entrypoint /6-881-examples/run_tests.sh
